[package]
name = "plugin-2021"
version = "0.1.0"
authors = ["fwcd"]
edition = "2018"

[dependencies]
socha-client-base = { path = "../client-base" }
log = "0.4"
arrayvec = "0.5"
itertools = "0.9"
regex = "1.4"
lazy_static = "1.4"
