[package]
name = "socha-client-base"
version = "0.1.0"
authors = ["fwcd"]
edition = "2018"

[dependencies]
log = "0.4"
indoc = "1.0"
quick-xml = { version = "0.22", features = ["serialize"] }
serde = { version = "1.0", features = ["derive"] }
