[package]
name = "socha-plugin-2020"
version = "0.1.0"
authors = ["fwcd"]
edition = "2018"

[dev-dependencies]
more-asserts = "0.2.1"

[dependencies]
socha-client-base = { path = "../client-base" }
log = "0.4.8"
arrayvec = "0.4.11"
itertools = "0.8.0"
regex = "1.3.1"
lazy_static = "1.4.0"
