[package]
name = "socha-plugin-2020"
version = "0.1.0"
authors = ["fwcd"]
edition = "2018"

[dependencies]
socha-client-base = { path = "../client-base" }
log = "0.4.8"
arrayvec = "0.4.11"
itertools = "0.8.0"
